### ISSUE TITLE
Resources for Circom

### ISSUE THREAD

**Issue by adrianmcli** [privacy-scaling-explorations/core-program#10]
Stage 1 was originally pure theory
Stage 2 was originally pure Circom practice

I think it makes sense to merge them into each other.

**Comment by adrianmcli** [comment]
Good ideas for getting ppl to practice Circom writing:
https://github.com/RareSkills/zero-knowledge-puzzles

**Comment by adrianmcli** [comment]
This also looks good: https://github.com/erhant/circom101

**Comment by NOOMA-42** [comment]
added in 2024 week2
