### ISSUE TITLE
Organize existing module to different week folder

### ISSUE THREAD

**Issue by NOOMA-42** [privacy-scaling-explorations/core-program#27]
### Summary

We need to organize existing module to different week folder, for example m2 m3 belongs to week 1

### Location

- Module Name:
- Section/Step:

### Proposed Correction

If you have a suggestion for how to fix the issue, please include it here.

### Screenshots (if applicable)

Attach any screenshots that might help explain the issue.

### Additional Context

Add any other information that might be helpful, such as links to related tutorials or explanations.

**Comment by adrianmcli** [comment]
I don't think we need specific week folders. I think we can just do everything for the new program in a new folder (see #28) and then when it's ready we replace everything with the new content. I don't want to nest everything within an extra level.
