### ISSUE TITLE
De-emphasize Pinocchio Protocol + Emphasize PLONK

### ISSUE THREAD

**Issue by adrianmcli** [privacy-scaling-explorations/core-program#3]
### Summary

After some feedback from students and researchers, it was agreed that while the Pinocchio Protocol plays an important historical role, it's not necessary to work through its details. Instead, it is more important to place the focus on PLONK as it underscores much of the modern techniques being developed.

### Location

- Module Name: Module 4 - zkSNARKs
- Section/Step: 3 and 4

### Proposed Correction

- [ ] Continue to mention the Pinocchio Protocol and highlight its historical importance (keep the links).
- [ ] However, explain to the reader that it is not necessary to understand its technical details.
- [ ] Expand the Section on PLONK.

### Notes

We might want to break this up into two issues as it targets to items. However, if someone can correct both in one PR, then even better.

**Comment by chokermaxx** [comment]
It would be great if the learning materials mentioned the maths required to understand Plonk!
- Schwartz Zippel Lemma https://brilliant.org/wiki/schwartz-zippel-lemma/
- Lagrange interpolation https://en.wikipedia.org/wiki/Lagrange_polynomial
- FFT https://www.youtube.com/watch?v=h7apO7q16V0
etc...
Things I struggled to grasp while learning Plonk was not Plonk itself but the maths upon which Plonk is built
